# Generated by Django 4.2.5 on 2023-10-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.SmallIntegerField(),
        ),
    ]
