# Generated by Django 4.2.5 on 2023-10-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
