# Generated by Django 4.2.5 on 2023-11-25 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyAdmin', '0001_initial'),
        ('Users', '0004_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('skills', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('IndustryModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyAdmin.industrymodel')),
                ('UserModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
