# Generated by Django 4.2.5 on 2023-11-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_internshipmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
