# Generated by Django 4.2.5 on 2023-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_internshipmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipmodel',
            name='stipend',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
