# Generated by Django 4.2.5 on 2023-12-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_feedbackstudentmodel_candidatemodel_bookmarkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
